### ISSUE TITLE
Usage

### ISSUE THREAD

**Issue by slowflyer** [johnboiles/NMEAProxy#2]
Hi,
I want to send all NMEA data captured from UART to an tcp port.

How does this work? All data should be send using 0.0.0.0 and port 4352

When using ./nmea_proxy.py --tcp 4352 --uart /dev/ttyAMA0 the proxy is listening on this port, but not sending? Is that correct?

**Comment by johnboiles** [comment]
That command looks right off the top of my head. Does it not run?

Everything connected to NMEAProxy should have a bidirectional connection: anything received from the UART will go out to other UARTs and TCP, anything received from TCP will go out the UARTs and other TCP connections.

Note that the `--tcp` option creates a server that a client connect to. NMEAProxy doesn't have the ability to initiate an outbound connection (though that would be a neat feature).

**Comment by johnboiles** [comment]
On second read it does appear that an outbound client tcp socket is what you wanted. Shouldn't be too hard to add if you want to try to add it. Maybe call the option`--tcp-client` and have it take a host and port like this `--tcp-client 127.0.0.1:4352`

**Comment by slowflyer** [comment]
Thanks for your help.

After stopping gpsd reading from /dev/ttyAMA0 my command from above worked and data read on UART has been send to port 4352.
gpsd send NMEA data on port 2947. But when I tried to start nmea_proxy with --tcp 2947 I received an error that this port is already in use.
My goal is to read nmea data from different sources and send all of them to a specific port.
